### ISSUE TITLE
Can you upload the build bin file 

### ISSUE THREAD

**Issue by najmulnirob80** [simbake/Openwrt-21.02-TL-WR840N-6.2#1]
Tried multiple time got error when making tools . can you please upload the bin file here or in gdrive please

**Comment by simbake** [comment]
Sorry I do not have built files anymore. What is the error while making tools?

**Comment by simbake** [comment]
Hi, please try the bin files form the link below. Know that I haven't tested it but should work for tl-wr840n 6.20.
What is included: SQM,firewall, no PPOE.

https://drive.google.com/drive/folders/1uroy02-NYTpWROyejrAS0796wy2mHGXq?usp=drive_link

Regards.

**Comment by simbake** [comment]
Closing due to no reply
