### ISSUE TITLE
Hi, could you please help me? There are some errors while building 

### ISSUE THREAD

**Issue by ToshiroADP** [simbake/Openwrt-21.02-TL-WR840N-6.2#2]
The error says something related to "stagin_dir host is unavailable"... Sorry, I can't send a screenshot. Also, could you please tell me the full instructions to build firmware for this router from cero? is it possible to use a newer version of openwrt? THank you so much in advance.

**Comment by simbake** [comment]
Newer versions of openwrt cannot fit in the router. You can try to setup an ubuntu 18 or 19 env and build there. The full instructions are in the readme.

**Comment by ToshiroADP** [comment]
Okay, thanks for your reply! I'll try to build it again today! I was using Ubuntu 22.04... but I'll follow your advice and install Ubuntu 18!

**Comment by ToshiroADP** [comment]
Hi again, I just wanted to let you know that everything worked! Thank you so much for your help!!!
